import Foundation

struct LocalizedKey {
    static let tabProjects = "tab.projects"
    static let tabMeasure = "tab.measure"
    static let tabSettings = "tab.settings"
    
    static let projectsTitle = "projects.title"
    static let projectsEmpty = "projects.empty"
    static let projectsEmptyDescription = "projects.empty.description"
    static let projectsNew = "projects.new"
    static let projectsCancel = "projects.cancel"
    static let projectsCreate = "projects.create"
    static let projectsNamePlaceholder = "projects.name.placeholder"
    static let projectsMeasurements = "projects.measurements"
    
    static let measurementTitle = "measurement.title"
    static let measurementRoomScan = "measurement.room.scan"
    static let measurementRoomScanDescription = "measurement.room.scan.description"
    static let measurementManual = "measurement.manual"
    static let measurementManualDescription = "measurement.manual.description"
    static let measurementTipsTitle = "measurement.tips.title"
    static let measurementTipLighting = "measurement.tip.lighting"
    static let measurementTipMovement = "measurement.tip.movement"
    static let measurementTipCamera = "measurement.tip.camera"
    static let measurementTipDistance = "measurement.tip.distance"
    static let measurementLevel = "measurement.level"
    static let measurmentSurfaceAngle = "measurement.surface.angle"
    
    static let arStatusExcessiveMotion = "ar.status.excessive.motion"
    static let arStatusInsufficientFeatures = "ar.status.insufficient.features"
    static let arStatusInitializing = "ar.status.initializing"
    static let arStatusRelocalizing = "ar.status.relocalizing"
    static let arMeasurement = "ar.measurement"
    static let arResult = "ar.result"
    static let arDetails = "ar.details"
    
    static let roomScanReady = "room.scan.ready"
    static let roomScanScanning = "room.scan.scanning"
    static let roomScanProcessing = "room.scan.processing"
    static let roomScanComplete = "room.scan.complete"
    static let roomScanError = "room.scan.error"
    static let roomScanProcessingError = "room.scan.processing.error"
    static let roomScanStart = "room.scan.start"
    static let roomScanStop = "room.scan.stop"
    static let roomScanInstructionMove = "room.scan.instruction.move"
    static let roomScanNotSupported = "room.scan.not.supported"
    static let roomScanCameraAccess = "room.scan.camera.access"
    
    static let projectInfo = "project.info"
    static let projectCreated = "project.created"
    static let projectRooms = "project.rooms"
    static let projectTotalArea = "project.total.area"
    static let projectExport = "project.export"
    static let projectExportPDF = "project.export.pdf"
    static let projectAddRoom = "project.add.room"
    static let projectRoomName = "project.room.name"
    static let projectDetailNoRooms = "project.detail.no.rooms"
    static let projectDetailNoRoomsDescription = "project.detail.no.rooms.description"
    static let projectDetailTime = "project.detail.time"
    
    static let roomMeasurements = "room.measurements"
    static let roomArea = "room.area"
    static let roomHeight = "room.height"
    static let roomWalls = "room.walls"
    static let roomWindows = "room.windows"
    static let roomDoors = "room.doors"
    static let roomAddMeasurement = "room.add.measurement"
    static let roomResultsExport3D = "room.results.export.3d"
    static let ARView = "room.ar.view"
    
    static let roomResultsTitle = "room.results.title"
    static let roomResultsSave = "room.results.save"
    static let roomLength = "room.length"
    static let roomWall = "room.wall"
    static let roomDoor = "room.door"
    static let roomWindow = "room.window"
    
    static let saveName = "save.name"
    static let saveNamePlaceholder = "save.name.placeholder"
    static let saveNotes = "save.notes"
    static let saveNotesPlaceholder = "save.notes.placeholder"
    static let saveDistance = "save.distance"
    static let saveSelectProject = "save.select.project"
    static let saveSelectRoom = "save.select.room"
    static let saveCreateRoom = "save.create.room"
    
    static let settingsTitle = "settings.title"
    static let settingsMain = "settings.main"
    static let settingsMeasurements = "settings.measurements"
    static let settingsUnits = "settings.units"
    static let settingsUnitsMetric = "settings.units.metric"
    static let settingsUnitsImperial = "settings.units.imperial"
    static let settingsHaptic = "settings.haptic"
    static let settingsData = "settings.data"
    static let settingsStorage = "settings.storage"
    static let settingsStorageManage = "settings.storage.manage"
    static let settingsLanguage = "settings.language"
    static let settingsAutoFlashlight = "settings.auto.flashlight"
    static let settingsAutoFlashlightHint = "settings.auto.flashlight.hint"
    
    static let storageTitle = "storage.title"
    static let storageUsage = "storage.usage"
    static let storageProjects = "storage.projects"
    static let storageMeasurements = "storage.measurements"
    static let storageSize = "storage.size"
    static let storageCalculating = "storage.calculating"
    static let storageClearAll = "storage.clear.all"
    static let storageClearConfirm = "storage.clear.confirm"
    static let storageClearMessage = "storage.clear.message"
        
    static let measurementObjectScan = "object.scan"
    static let measurementObjectScanDescription = "object.scan.description"
    static let objectMeasureHint = "object.measure.hint"
    
    static let commonCancel = "common.cancel"
    static let commonSave = "common.save"
    static let commonDelete = "common.delete"
    static let commonDone = "common.done"
    static let commonClose = "common.close"
    static let commonOK = "common.ok"
    static let commonError = "common.error"
    
    static let unitMeters = "unit.meters"
    static let unitCentimeters = "unit.centimeters"
    static let unitFeet = "unit.feet"
    static let unitInches = "unit.inches"
    static let unitSquareMeters = "unit.square.meters"
    static let unitSquareFeet = "unit.square.feet"
    static let unitCubicMeters = "unit.cubic.meters"
    static let unitCubicFeet = "unit.cubic.feet"
    
    static let languageRussian = "language.russian"
    static let languageEnglish = "language.english"
    
    static let projectDetailRename = "project.detail.rename"
    static let projectDetailExport = "project.detail.export"
    static let projectDetailInformation = "project.detail.information"
    static let projectDetailRoomsCount = "project.detail.rooms.count"
    static let projectDetailStatistics = "project.detail.statistics"
    static let projectDetailTotalVolume = "project.detail.total.volume"
    static let projectDetail3DScan = "project.detail.3d.scan"
    static let projectDetailProjectName = "project.detail.project.name"
    static let projectDetailNewName = "project.detail.new.name"
    static let projectDetailLoading3D = "project.detail.loading.3d"
    static let projectDetailLoadingError = "project.detail.loading.error"
    static let projectDetail3DModel = "project.detail.3d.model"
    static let projectDetailNotesTitle = "project.detail.notes.title"
    static let projectDetailRoomNotes = "project.detail.room.notes"
    static let projectDetailCanAddLater = "project.detail.can.add.later"
    static let projectDetailFileSize = "project.detail.file.size"
    static let projectDetailAddNotes = "project.detail.add.notes"
    static let projectDetailActions = "project.detail.actions"
    static let projectDetailRescanRoom = "project.detail.rescan.room"
    
    static let arMeasurementFirstPoint = "ar.measurement.first.point"
    static let arMeasurementSecondPoint = "ar.measurement.second.point"
    static let arMeasurementClear = "ar.measurement.clear"
    static let arMeasurementPoint = "ar.measurement.point"
    static let arMeasurementTrackingReady = "ar.measurement.tracking.ready"
    static let arMeasurementTrackingUnavailable = "ar.measurement.tracking.unavailable"
    static let arMeasurementTrackingExcessiveMotion = "ar.measurement.tracking.excessive.motion"
    static let arMeasurementTrackingInsufficientFeatures = "ar.measurement.tracking.insufficient.features"
    static let arMeasurementTrackingInitializing = "ar.measurement.tracking.initializing"
    static let arMeasurementTrackingRelocalizing = "ar.measurement.tracking.relocalizing"
    static let arMeasurementTrackingLimited = "ar.measurement.tracking.limited"
    static let arMeasurementTrackingError = "ar.measurement.tracking.error"
    static let arMeasurementTrackingStopped = "ar.measurement.tracking.stopped"
    static let arMeasurementTrackingInterrupted = "ar.measurement.tracking.interrupted"
    static let arInstructionSecond = "ar.instruction.second"
    
    static let projectSelectorTitle = "project.selector.title"
    static let projectSelectorCancel = "project.selector.cancel"
    static let projectSelector3DScan = "project.selector.3d.scan"
    static let projectSelectorManualMeasurement = "project.selector.manual.measurement"
    static let projectSelectorSelectProjectRoom = "project.selector.select.project.room"
    static let projectSelectorNoProjects = "project.selector.no.projects"
    static let projectSelectorCreateProjectMessage = "project.selector.create.project.message"
    static let projectSelectorCreateProject = "project.selector.create.project"
    static let projectSelectorProject = "project.selector.project"
    static let projectSelectorCreate = "project.selector.create"
    static let projectSelectorRoomRequired = "project.selector.room.required"
    static let projectSelectorRoomAdd = "project.selector.room.add"
    static let projectSelectorNoRooms = "project.selector.no.rooms"
    static let projectSelectorCreateRoomContinue = "project.selector.create.room.continue"
    static let projectSelectorProceed = "project.selector.proceed"
    static let projectSelectorSelectRoomFirst = "project.selector.select.room.first"
    static let projectSelectorNewProjectTitle = "project.selector.new.project.title"
    static let projectSelectorProjectInfo = "project.selector.project.info"
    static let projectSelectorProjectNamePlaceholder = "project.selector.project.name.placeholder"
    static let projectSelectorNewRoomTitle = "project.selector.new.room.title"
    static let projectSelectorRoomNameTitle = "project.selector.room.name.title"
    static let projectSelectorRoomNamePlaceholder = "project.selector.room.name.placeholder"
    static let projectSelectorPopularNames = "project.selector.popular.names"
    static let projectSelectorRoomLiving = "project.selector.room.living"
    static let projectSelectorRoomKitchen = "project.selector.room.kitchen"
    static let projectSelectorRoomBedroom = "project.selector.room.bedroom"
    static let projectSelectorRoomBathroom = "project.selector.room.bathroom"
    static let projectSelectorRoomHallway = "project.selector.room.hallway"
    static let projectSelectorRoomBalcony = "project.selector.room.balcony"
    static let projectSelectorAddButton = "project.selector.add.button"
    
    static let saveMeasurementTitle = "save.measurement.title"
    
    static let settingsTheme = "settings.theme"
    static let themeLightMode = "theme.light.mode"
    static let themeDarkMode = "theme.dark.mode"
    
    static let floorPlanTitle = "floor.plan.title"
    static let floorPlanDoor = "floor.door"
    static let floorPlanWindow = "floor.window"
    static let commonShare =  "floor.share"
    
    static let spaceTitle = "space.title"
    static let object3DTitle = "3d.object.title"
    static let rulerTitle = "ruler.title"
    static let levelTitle = "level.title"
    
    static let objectScanToolTitle = "object.scan.tool.title"
}
